/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Puzzlepck;

import java.util.Random;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author 0040481722019
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTimer = new javax.swing.JLabel();
        lblMov = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        jButton9.setText("jButton1");

        jButton8.setText("jButton1");

        jButton7.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Puzzle");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(122, 50, 50));

        jPanel2.setBackground(new java.awt.Color(67, 75, 194));

        lblTimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 255, 255));
        lblTimer.setText("Tempo : 00:00:00");

        lblMov.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMov.setForeground(new java.awt.Color(255, 255, 255));
        lblMov.setText("Movimento: 0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMov, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMov, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(164, 53, 53));

        btn00.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn00.setText("1");
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn01.setText("2");
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        btn02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn02.setText("3");
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn10.setText("4");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn11.setText("5");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn12.setText("6");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn20.setText("7");
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btn21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn21.setText("8");
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Game");

        jMenuItem1.setText("Novo Jogo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         Shuffle();
         qtdMov= 0;
         lblMov.setText("Movimento: " + qtdMov);
         tempo = true;
         count = 0;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        tempo = false;
        JOptionPane.showMessageDialog(null, "Paulo Mello\nAnalise e Desenvolvimento de Sistemas\nEletiva em JAVA", "Sobre", JOptionPane.OK_OPTION);
        tempo = true;
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        NextMove(0, 0);
        checkPuzzle();
    }//GEN-LAST:event_btn00ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pos[0][0] = '1';
        pos[0][1] = '2';
        pos[0][2] = '3';
        pos[1][0] = '4';
        pos[1][1] = '5';
        pos[1][2] = '6';
        pos[2][0] = '7';
        pos[2][1] = '8';
        pos[2][2] = ' ';
        Shuffle();
        qtdMov= 0;
        lblMov.setText("Movimento: " + qtdMov);
        Cronometro();
    }//GEN-LAST:event_formWindowOpened

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        NextMove(0, 1);
        checkPuzzle();
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        NextMove(0, 2);
        checkPuzzle();
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        NextMove(1, 0);
        checkPuzzle();
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        NextMove(1, 1);
        checkPuzzle();
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        NextMove(1, 2);
        checkPuzzle();
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        NextMove(2, 0);
        checkPuzzle();
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        NextMove(2, 1);
        checkPuzzle();
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        NextMove(2, 2);
        checkPuzzle();
    }//GEN-LAST:event_btn22ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainFrame().setVisible(true);
        });
    }

    void attCelula() {
        btn00.setText(String.valueOf(pos[0][0]));
        btn01.setText(String.valueOf(pos[0][1]));
        btn02.setText(String.valueOf(pos[0][2]));
        btn10.setText(String.valueOf(pos[1][0]));
        btn11.setText(String.valueOf(pos[1][1]));
        btn12.setText(String.valueOf(pos[1][2]));
        btn20.setText(String.valueOf(pos[2][0]));
        btn21.setText(String.valueOf(pos[2][1]));
        btn22.setText(String.valueOf(pos[2][2]));
    }

    void checkPuzzle() {
        if (    pos[0][0] == '1'
                && pos[0][1] == '2'
                && pos[0][2] == '3'
                && pos[1][0] == '4'
                && pos[1][1] == '5'
                && pos[1][2] == '6'
                && pos[2][0] == '7'
                && pos[2][1] == '8'
                && pos[2][2] == ' ') {
            tempo = false;
            JOptionPane.showMessageDialog(null, "Parabéns!!\nTempo de Jogo: "+ String.format("%02d:%02d:%02d",HH,mm,ss)+
                    "\nMovimentos: "+ String.format("%03d",qtdMov), "Fim de Jogo!", JOptionPane.OK_OPTION);
            Shuffle();
            qtdMov= 0;
            lblMov.setText("Movimento: " + qtdMov);
            tempo = true;
            count = 0;
        }
    }

    void attMov() {
        qtdMov++;
        lblMov.setText("Movimento: " + qtdMov);
    }

    void Shuffle() {
        int vezes = rand.nextInt(100)+51;
        for (int i = 0; i <= vezes; i++) {
                for (int x = 0; x <= 2; x++) {
                    for (int y = 0; y <= 2; y++) {
                        if (pos[x][y] == ' ') {
                            RandomMove(x, y);
                        }
                    }
                }
            }
    }

    void RandomMove(int x, int y)
    { //
        int t =0;
        //2 randoms
        if((x==0 && y==0))
        {
            t = rand.nextInt(2)+1;
            if(t==1)
                NextMove(1,0);
            else
                NextMove(0,1);
        }
        else if((x==0 && y==2))
        {
            t = rand.nextInt(2)+1;
            if(t==1)
                NextMove(0,1);
            else
                NextMove(1,2);
        }
        else if((x==2 && y==0))
        {
            t = rand.nextInt(2)+1;
            if(t==1)
                NextMove(1,0);
            else
                NextMove(2,1);
        }
        else if((x==2 && y==2))
        {
            t = rand.nextInt(2)+1;
            if(t==1)
                NextMove(2,1);
            else
                NextMove(1,2);
        }
        //3 randoms
        if((x==0 && y==1))
        {
            t = rand.nextInt(3)+1;
            switch (t) {
                case 1:
                    NextMove(0,0);
                    break;
                case 2:
                    NextMove(1,1);
                    break;
                default:
                    NextMove(0,2);
                    break;
            }
        }
        else if((x==1 && y==2))
        {
            t = rand.nextInt(3)+1;
            switch (t) {
                case 1:
                    NextMove(0,2);
                    break;
                case 2:
                    NextMove(1,1);
                    break;
                default:
                    NextMove(2,2);
                    break;
            }
        }
        else if((x==2 && y==1))
        {
            t = rand.nextInt(3)+1;
            switch (t) {
                case 1:
                    NextMove(2,2);
                    break;
                case 2:
                    NextMove(1,1);
                    break;
                default:
                    NextMove(2,0);
                    break;
            }
        }
        else if((x==1 && y==0))
        {
            t = rand.nextInt(3)+1;
            switch (t) {
                case 1:
                    NextMove(0,0);
                    break;
                case 2:
                    NextMove(1,1);
                    break;
                default:
                    NextMove(2,0);
                    break;
            }
        }
        //4randoms
        else if((x==1 && y==1))
        {
            t = rand.nextInt(4)+1;
            switch (t) {
                case 1:
                    NextMove(0,1);
                    break;
                case 2:
                    NextMove(1,0);
                    break;
                case 3:
                    NextMove(2,1);
                    break;
                default:
                    NextMove(1,2);
                    break;
            }
        }
    }
    
    void NextMove(int x, int y) {
        //pos[0][0]
        if (x == 0 && y == 0) {
            if (pos[0][0] == ' ') {
                return;
            }
            if (pos[1][0] == ' ') {
                pos[1][0] = pos[0][0];
                pos[0][0] = ' ';
                attMov();
            } else if (pos[0][1] == ' ') {
                pos[0][1] = pos[0][0];
                pos[0][0] = ' ';
                attMov();
            }
        } 
        //pos[0][1]
        else if (x == 0 && y == 1) {
            if (pos[0][1] == ' ') {
                return;
            }
            if (pos[0][0] == ' ') {
                pos[0][0] = pos[0][1];
                pos[0][1] = ' ';
                attMov();
            } else if (pos[1][1] == ' ') {
                pos[1][1] = pos[0][1];
                pos[0][1] = ' ';
                attMov();
            } else if (pos[0][2] == ' ') {
                pos[0][2] = pos[0][1];
                pos[0][1] = ' ';
                attMov();
            }
        } 
        //pos[0][2]
        else if (x == 0 && y == 2) {
            if (pos[0][2] == ' ') {
                return;
            }
            if (pos[0][1] == ' ') {
                pos[0][1] = pos[0][2];
                pos[0][2] = ' ';
                attMov();
            }
            if (pos[1][2] == ' ') {
                pos[1][2] = pos[0][2];
                pos[0][2] = ' ';
                attMov();
            }
        }
        //pos[1][0]
        else if (x == 1 && y == 0) {
            if (pos[1][0] == ' ') {
                return;
            }
            if (pos[0][0] == ' ') {
                pos[0][0] = pos[1][0];
                pos[1][0] = ' ';
                attMov();
            } else if (pos[1][1] == ' ') {
                pos[1][1] = pos[1][0];
                pos[1][0] = ' ';
                attMov();
            } else if (pos[2][0] == ' ') {
                pos[2][0] = pos[1][0];
                pos[1][0] = ' ';
                attMov();
            }
        }
        //pos[1][1]
        else if (x == 1 && y == 1) {
            if (pos[1][1] == ' ') {
                return;
            }
            if (pos[0][1] == ' ') {
                pos[0][1] = pos[1][1];
                pos[1][1] = ' ';
                attMov();
            } else if (pos[1][2] == ' ') {
                pos[1][2] = pos[1][1];
                pos[1][1] = ' ';
                attMov();
            } else if (pos[2][1] == ' ') {
                pos[2][1] = pos[1][1];
                pos[1][1] = ' ';
                attMov();
            } else if (pos[1][0] == ' ') {
                pos[1][0] = pos[1][1];
                pos[1][1] = ' ';
                attMov();
            }
        } 
        //pos[1][2]
        else if (x == 1 && y == 2) {
            if (pos[1][2] == ' ') {
                return;
            }
            if (pos[0][2] == ' ') {
                pos[0][2] = pos[1][2];
                pos[1][2] = ' ';
                attMov();
            } else if (pos[1][1] == ' ') {
                pos[1][1] = pos[1][2];
                pos[1][2] = ' ';
                attMov();
            } else if (pos[2][2] == ' ') {
                pos[2][2] = pos[1][2];
                pos[1][2] = ' ';
                attMov();
            }
        } 
        //pos[2][0]
        else if (x == 2 && y == 0) {
            if (pos[2][0] == ' ') {
                return;
            }
            if (pos[2][1] == ' ') {
                pos[2][1] = pos[2][0];
                pos[2][0] = ' ';
                attMov();
            } else if (pos[1][0] == ' ') {
                pos[1][0] = pos[2][0];
                pos[2][0] = ' ';
                attMov();
            }
        }
        //pos[2][1]
        else if (x == 2 && y == 1) {
            if (pos[2][1] == ' ') {
                return;
            }
            if (pos[2][0] == ' ') {
                pos[2][0] = pos[2][1];
                pos[2][1] = ' ';
                attMov();
            } else if (pos[1][1] == ' ') {
                pos[1][1] = pos[2][1];
                pos[2][1] = ' ';
                attMov();
            } else if (pos[2][2] == ' ') {
                pos[2][2] = pos[2][1];
                pos[2][1] = ' ';
                attMov();
            }
        }
        //pos[2][2]
        else if (x == 2 && y == 2) {
            if (pos[2][2] == ' ') {
                return;
            }
            if (pos[2][1] == ' ') {
                pos[2][1] = pos[2][2];
                pos[2][2] = ' ';
                attMov();
            } else if (pos[1][2] == ' ') {
                pos[1][2] = pos[2][2];
                pos[2][2] = ' ';
                attMov();
            }
        }
        attCelula();
    }

    void Cronometro()
    {
        new java.util.Timer().schedule(new TimerTask() {
        @Override
        public void run() {
            if(tempo)
            {
                count++;
                int seg = count % 60;
                int min = count / 60;
                int hora = min/60;
                min %= 60;
                lblTimer.setText(String.format("Tempo: %02d:%02d:%02d",hora,min,seg));
                HH = hora;
                mm = min;
                ss = seg;
            }
        }
        }, 1000,1000); 
    }
    
    private int HH,mm,ss;
    private boolean tempo = true;
    private final char[][] pos = new char[3][3];
    private int qtdMov;
    private int count;
    private final Random rand = new Random();  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblMov;
    private javax.swing.JLabel lblTimer;
    // End of variables declaration//GEN-END:variables
}
